# Generated by Django 5.2.1 on 2025-05-28 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка на изображение')),
                ('category', models.CharField(choices=[('books', 'Книги'), ('clothes', 'Одежда'), ('appliances', 'Бытовая техника'), ('furniture', 'Мебель'), ('toys', 'Игрушки'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('old', 'Старый')], default='new', max_length=10, verbose_name='Условие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'ожидает'), ('accepted', 'принята'), ('rejected', 'отклонена')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_receiver_id', to='ads.ad', verbose_name='Получатель')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_sender_id', to='ads.ad', verbose_name='Отправитель')),
            ],
        ),
    ]
